name: smart_irrigation
description: "A Smart Irrigation System Dashboard using Flutter and Firebase."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0  
  firebase_database: ^11.0.0
  percent_indicator: ^4.2.3  
  google_fonts: ^6.2.1
  flutter_local_notifications: ^17.0.0
  flutter_background_service: ^5.0.0
  firebase_messaging: ^15.0.0
  file_picker: ^8.0.0
  firebase_storage: ^12.0.0
  http: ^1.6.0
  url_launcher: ^6.3.2
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
